from __future__ import annotations

USER_PENDING_APPROVAL = "user_pending_approval"
ADMIN_ACCESS_REQUIRED = "admin_access_required"
ADMIN_USER_NOT_FOUND = "admin_user_not_found"
THREAD_NOT_FOUND = "thread_not_found"
UNKNOWN_TOOLS = "unknown_tools"
LAST_ACTIVE_ADMIN = "last_active_admin"
SELF_DEACTIVATE_ADMIN = "self_deactivate_admin"
WHM_SERVER_NOT_FOUND = "whm_server_not_found"
WHM_SERVER_NAME_EXISTS = "whm_server_name_exists"
MESSAGE_EDIT_NOT_SUPPORTED = "message_edit_not_supported"
INVALID_ADD_MESSAGE_ROLE = "invalid_add_message_role"
MISSING_TOOL_CALL_ID = "missing_tool_call_id"
INVALID_TOOL_CALL_ID = "invalid_tool_call_id"
UNKNOWN_TOOL_CALL_ID = "unknown_tool_call_id"
TOOL_CALL_NOT_FOUND = "tool_call_not_found"
TOOL_CALL_NOT_AWAITING_RESULT = "tool_call_not_awaiting_result"
MISSING_ACTION_REQUEST_ID = "missing_action_request_id"
INVALID_ACTION_REQUEST_ID = "invalid_action_request_id"
ACTION_REQUEST_NOT_FOUND = "action_request_not_found"
ACTION_REQUEST_ALREADY_DECIDED = "action_request_already_decided"
CHANGE_APPROVAL_REQUIRED = "change_approval_required"
TOOL_ACCESS_DENIED = "tool_access_denied"
