"""Shared column helpers (V66 — reuse over duplication).

Every table repeats the same three shapes: a server-generated UUID primary key,
created/updated timestamps, and encrypted-secret text. Declaring them once keeps
the models readable and the DDL uniform.
"""

from __future__ import annotations

from datetime import datetime
from uuid import UUID

from sqlalchemy import DateTime, Text, func
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column


def uuid_pk() -> Mapped[UUID]:
    """UUID primary key generated by Postgres (`gen_random_uuid()`, pgcrypto/PG13+)."""
    return mapped_column(
        PG_UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )


def created_at() -> Mapped[datetime]:
    """Insert timestamp, timezone-aware, DB-defaulted."""
    return mapped_column(DateTime(timezone=True), nullable=False, server_default=func.now())


def updated_at() -> Mapped[datetime]:
    """Mutation timestamp; DB default on insert, ORM-maintained on update."""
    return mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )


def encrypted_secret() -> Mapped[str]:
    """Required credential column holding ciphertext (C7, V48).

    Value format is `enc:v1:fernet:...`; plaintext never lands here. `Text` because
    Fernet output length tracks the plaintext and has no useful bound.
    """
    return mapped_column(Text, nullable=False)


def optional_encrypted_secret() -> Mapped[str | None]:
    """Nullable variant of :func:`encrypted_secret` (credential not configured)."""
    return mapped_column(Text, nullable=True)


class TimestampMixin:
    """Adds `created_at` / `updated_at` to a model."""

    created_at: Mapped[datetime] = created_at()
    updated_at: Mapped[datetime] = updated_at()
