"""Shared column helpers (V66 — reuse over duplication).

Every table repeats the same shapes: a server-generated UUID primary key,
created/updated timestamps, encrypted-secret text, and — since T35 — lifecycle
enum columns. Declaring them once keeps the models readable and the DDL uniform.
"""

from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from typing import Any
from uuid import UUID

from sqlalchemy import DateTime, Enum, Text, func
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column


def uuid_pk() -> Mapped[UUID]:
    """UUID primary key generated by Postgres (`gen_random_uuid()`, pgcrypto/PG13+)."""
    return mapped_column(
        PG_UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )


def created_at(**kwargs: Any) -> Mapped[datetime]:
    """Insert timestamp, timezone-aware, DB-defaulted.

    `**kwargs` reaches `mapped_column` — `tool_runs` passes `index=True` because the
    audit list sorts and pages on it (T35, T55), and no other table needs that index.
    """
    return mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(), **kwargs
    )


def updated_at() -> Mapped[datetime]:
    """Mutation timestamp; DB default on insert, ORM-maintained on update."""
    return mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )


def lifecycle_enum_type(enum_class: type[StrEnum], *, name: str) -> Enum:
    """A `core.db.lifecycle` enum stored as a checked VARCHAR (V20).

    `native_enum=False` keeps it out of Postgres' own enum types: adding a member to a
    native enum is `ALTER TYPE`, which cannot run inside a transaction block on older
    servers and leaves the type behind on downgrade. A VARCHAR plus a CHECK constraint
    is dropped with the table.

    `create_constraint=True` is the point of the helper — SQLAlchemy 2.0 defaults it to
    `False`, which would leave `native_enum=False` as a plain unconstrained VARCHAR and
    V20's "machine-stable" resting on application code alone. With the constraint, a
    renamed member fails at the DB and has to be a migration.

    `validate_strings=True` catches the same mistake earlier, on the Python side, before
    a flush.
    """
    return Enum(
        enum_class,
        name=name,
        native_enum=False,
        create_constraint=True,
        validate_strings=True,
    )


def lifecycle_enum(
    enum_class: type[StrEnum], *, name: str, default: StrEnum | None = None, **kwargs: Any
) -> Mapped[Any]:
    """Required lifecycle-enum column, optionally DB-defaulted (V20)."""
    server_default = default.value if default is not None else None
    return mapped_column(
        lifecycle_enum_type(enum_class, name=name),
        nullable=False,
        server_default=server_default,
        **kwargs,
    )


def encrypted_secret() -> Mapped[str]:
    """Required credential column holding ciphertext (C7, V48).

    Value format is `enc:v1:fernet:...`; plaintext never lands here. `Text` because
    Fernet output length tracks the plaintext and has no useful bound.
    """
    return mapped_column(Text, nullable=False)


def optional_encrypted_secret() -> Mapped[str | None]:
    """Nullable variant of :func:`encrypted_secret` (credential not configured)."""
    return mapped_column(Text, nullable=True)


class TimestampMixin:
    """Adds `created_at` / `updated_at` to a model."""

    created_at: Mapped[datetime] = created_at()
    updated_at: Mapped[datetime] = updated_at()
