"""Shared column helpers (reuse over duplication).

Every table repeats the same shapes: a server-generated UUID primary key,
created/updated timestamps, encrypted-secret text, and — since the `tool_runs` table —
lifecycle enum columns. Declaring them once keeps the models readable and the DDL uniform.
"""

from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from typing import Any
from uuid import UUID

from sqlalchemy import DateTime, Enum, Text, func
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column

from core.clock import now_utc


def uuid_pk() -> Mapped[UUID]:
    """UUID primary key generated by Postgres (`gen_random_uuid()`, pgcrypto/PG13+)."""
    return mapped_column(
        PG_UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )


def created_at(**kwargs: Any) -> Mapped[datetime]:
    """Insert timestamp, timezone-aware, stamped by the application clock.

    One clock for every timestamp NOA writes. `default` makes the ORM stamp this column from
    `core.clock.now_utc`, which is where `decided_at`, `expires_at` and `completed_at` already
    come from. The API host and the database host are not guaranteed to agree — measured 38
    seconds apart on this deployment on 2026-09-12 — and a row whose start came from one host
    and whose end came from the other reports a duration off by that gap, or a completion
    stamped earlier than its own start.

    `server_default` stays as the fallback for rows inserted outside the ORM (Alembic, `psql`),
    so this needs no DDL change.

    Spelled `lambda: now_utc()` rather than `default=now_utc`: the lambda resolves the name at
    call time, which is what lets a test pin the clock and watch an assertion fail against
    unmodified production code. The bare reference is the tidier spelling and captures the
    function at import — do not simplify it back.

    `**kwargs` reaches `mapped_column` — `tool_runs` passes `index=True` because the
    audit list sorts and pages on it, and no other table needs that index.
    """
    return mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: now_utc(),
        server_default=func.now(),
        **kwargs,
    )


def updated_at() -> Mapped[datetime]:
    """Mutation timestamp, from the application clock on insert and on update.

    Both sides go through `core.clock.now_utc`, and both are spelled as a lambda, for the
    reasons :func:`created_at` gives. `server_default` remains the non-ORM fallback; `onupdate`
    has no server-side counterpart either way, so an UPDATE issued outside the ORM has never
    touched this column.
    """
    return mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: now_utc(),
        server_default=func.now(),
        onupdate=lambda: now_utc(),
    )


def lifecycle_enum_type(enum_class: type[StrEnum], *, name: str) -> Enum:
    """A `core.db.lifecycle` enum stored as a checked VARCHAR.

    `native_enum=False` keeps it out of Postgres' own enum types: adding a member to a
    native enum is `ALTER TYPE`, which cannot run inside a transaction block on older
    servers and leaves the type behind on downgrade. A VARCHAR plus a CHECK constraint
    is dropped with the table.

    `create_constraint=True` is the point of the helper — SQLAlchemy 2.0 defaults it to `False`,
    which would leave `native_enum=False` as a plain unconstrained VARCHAR and the lifecycle enums'
    "machine-stable" contract resting on application code alone. With the constraint, a renamed
    member fails at the DB and has to be a migration.

    `validate_strings=True` catches the same mistake earlier, on the Python side, before
    a flush.
    """
    return Enum(
        enum_class,
        name=name,
        native_enum=False,
        create_constraint=True,
        validate_strings=True,
    )


def lifecycle_enum(
    enum_class: type[StrEnum], *, name: str, default: StrEnum | None = None, **kwargs: Any
) -> Mapped[Any]:
    """Required lifecycle-enum column, optionally DB-defaulted."""
    server_default = default.value if default is not None else None
    return mapped_column(
        lifecycle_enum_type(enum_class, name=name),
        nullable=False,
        server_default=server_default,
        **kwargs,
    )


def encrypted_secret() -> Mapped[str]:
    """Required credential column holding ciphertext.

    Value format is `enc:v1:fernet:...`; plaintext never lands here. `Text` because
    Fernet output length tracks the plaintext and has no useful bound.
    """
    return mapped_column(Text, nullable=False)


def optional_encrypted_secret() -> Mapped[str | None]:
    """Nullable variant of :func:`encrypted_secret` (credential not configured)."""
    return mapped_column(Text, nullable=True)


class TimestampMixin:
    """Adds `created_at` / `updated_at` to a model."""

    created_at: Mapped[datetime] = created_at()
    updated_at: Mapped[datetime] = updated_at()
